version: '3.9'

services:
  spark:
    image: apache/spark:3.5.3
    user: 185:185
    container_name: spark
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - './scripts:/opt/spark/work-dir/scripts'
      - './input:/opt/spark/work-dir/input'
      - './output:/opt/spark/work-dir/spark-warehouse'
      - './logs:/opt/spark/work-dir/logs'
    environment:
      SPARK_MODE: 'master'
      SPARK_RPC_AUTHENTICATION_ENABLED: 'no'
      SPARK_RPC_ENCRYPTION_ENABLED: 'no'
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: 'no'
      SPARK_SSL_ENABLED: 'no'
      KAFKA_SERVERS: 'kafka:9092,kafka:9093'
    command: ['/opt/spark/bin/spark-class', 'org.apache.spark.deploy.master.Master']

  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    profiles:
      - 'kafka'
      - 'kafka-ui'
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  kafka-ui:
      profiles:
        - 'kafka-ui'
      container_name: kafka-ui
      image: provectuslabs/kafka-ui:latest
      ports:
        - 9000:8080
      environment:
        DYNAMIC_CONFIG_ENABLED: "true"
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      depends_on:
        - kafka
