version: '3.9'

services:
  spark:
    image: apache/spark:3.5.3
    user: 185:185
    container_name: spark
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - './scripts:/opt/spark/work-dir/scripts'
      - './input:/opt/spark/work-dir/input'
      - './output:/opt/spark/work-dir/spark-warehouse'
      - './logs:/opt/spark/work-dir/logs'
    environment:
      SPARK_MODE: 'master'
      SPARK_RPC_AUTHENTICATION_ENABLED: 'no'
      SPARK_RPC_ENCRYPTION_ENABLED: 'no'
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: 'no'
      SPARK_SSL_ENABLED: 'no'
    command: ['/opt/spark/bin/spark-class', 'org.apache.spark.deploy.master.Master']
