[project]
name = "spark-training"
version = "0.1.0"
description = "Personal Spark Training"
authors = ["Pavlo Prokhorenko <paulprokhorenko@gmail.com>"]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyspark==3.5.3",
]
